-- PaTiAuras settings. Run via PaTiAdmin/tools/check.sh.
local wow = require("wow_api")

local function load()
    return wow.loadAddonFile("Config.lua", {}).Config
end

describe("Config.Migrate", function()
    it("creates all defaults for a new character", function()
        local db = load().Migrate(nil)
        assert.is_true(db.enabled)
        assert.equal(1, db.scale)
        assert.equal("auto", db.language)
        assert.same({}, db.watch)
        assert.equal(1, db.schema)
    end)

    it("keeps saved values, also false, and the position", function()
        local db = load().Migrate({ showTimers = false, locked = true, scale = 1.25, x = 5, point = "TOPLEFT",
            watch = { RIPTIDE = false }, lastChangelog = "0.1.0" })
        assert.is_false(db.showTimers)
        assert.is_true(db.locked)
        assert.equal(1.25, db.scale)
        assert.equal(5, db.x)
        assert.equal("TOPLEFT", db.point)
        assert.is_false(db.watch.RIPTIDE)
        assert.equal("0.1.0", db.lastChangelog)
    end)
end)

describe("Config.RestoreDefaults", function()
    it("resets settings and watches but keeps position and changelog marker", function()
        local db = load().RestoreDefaults({ showTimers = false, scale = 1.5, x = 5, watch = { RIPTIDE = false },
            lastChangelog = "0.1.0" })
        assert.is_true(db.showTimers)
        assert.equal(1, db.scale)
        assert.same({}, db.watch)
        assert.equal(5, db.x)
        assert.equal("0.1.0", db.lastChangelog)
    end)
end)

describe("Config.NewDefs / seen", function()
    it("starts with nothing seen and keeps seen auras across Restore Defaults", function()
        local Config = load()
        local db = Config.Migrate({ watch = { RIPTIDE = false } })
        assert.same({}, db.seen)
        db.seen.INNER_FIRE = true
        Config.RestoreDefaults(db)
        assert.is_true(db.seen.INNER_FIRE)
    end)

    it("returns only the entries not offered before, in profile order", function()
        local defs = { { key = "INNER_FIRE" }, { key = "FORTITUDE" }, { key = "DIVINE_SPIRIT" } }
        local new = load().NewDefs(defs, { FORTITUDE = true })
        assert.equal(2, #new)
        assert.equal("INNER_FIRE", new[1].key)
        assert.equal("DIVINE_SPIRIT", new[2].key)
        assert.same({}, load().NewDefs(defs, { INNER_FIRE = true, FORTITUDE = true, DIVINE_SPIRIT = true }))
    end)
end)

describe("Collapse state", function()
    it("old saves get collapsed = false, a saved true stays, position is kept", function()
        local Config = load()
        assert.is_false(Config.Migrate({ x = 5 }).collapsed)
        local db = Config.Migrate({ x = 5, collapsed = true })
        assert.is_true(db.collapsed)
        assert.equal(5, db.x)
    end)

    it("Restore Defaults expands the window (documented) and keeps the position", function()
        local db = load().RestoreDefaults({ collapsed = true, x = 5 })
        assert.is_false(db.collapsed)
        assert.equal(5, db.x)
    end)
end)

describe("Weapon imbue setting", function()
    it("is on for older saves without touching their settings; a saved false stays", function()
        local Config = load()
        local db = Config.Migrate({ schema = 1, collapsed = true, locked = true, scale = 0.9, language = "deDE",
            x = 3, watch = { RIPTIDE = false }, seen = { RIPTIDE = true } })
        assert.is_true(db.showWeapon)
        assert.same({ true, true, 0.9, "deDE", 3 }, { db.collapsed, db.locked, db.scale, db.language, db.x })
        assert.same({ RIPTIDE = false }, db.watch)
        assert.same({ RIPTIDE = true }, db.seen)
        assert.is_false(Config.Migrate({ showWeapon = false }).showWeapon)
    end)
end)

describe("Window settings (panel opacity, snapping)", function()
    it("old saves get 75 % and snapping on; saved values stay; Restore Defaults resets them", function()
        local M = load()
        local db = M.Migrate({ x = 12, y = 34 })
        assert.equal(0.75, db.opacity)
        assert.is_true(db.snapWindows)
        assert.equal(12, db.x)
        db = M.Migrate({ opacity = 0.4, snapWindows = false })
        assert.equal(0.4, db.opacity)
        assert.is_false(db.snapWindows)
        db = M.RestoreDefaults({ opacity = 0.4, snapWindows = false, bindings = {}, bindingRanks = {}, watch = {} })
        assert.equal(0.75, db.opacity)
        assert.is_true(db.snapWindows)
    end)
end)
